<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>

<h2>Explore</h2>
<nav class="sub-menu">
<ul class="navigation">
	<li><a href="https://feuilleton.judaic.lsa.umich.edu/s/below-the-line/page/explore">Feuilletons</a></li>
	<li><a href="https://feuilleton.judaic.lsa.umich.edu/s/below-the-line/page/explore#authors">Authors</a></li>
	<li><a href="https://feuilleton.judaic.lsa.umich.edu/s/below-the-line/page/explore#newspapers">Newspapers</a></li>
	<li><a href="https://feuilleton.judaic.lsa.umich.edu/s/below-the-line/page/explore#languages">Languages</a></li>
	<li><a href="https://feuilleton.judaic.lsa.umich.edu/s/below-the-line/page/explore#places">Places</a></li>
</ul>
</nav>

<?php echo $this->pageTitle($item->displayTitle(), 3); ?>

<?php $this->trigger('view.show.before'); ?>

<section class="item_sets">
	<div class="property">
		<?php $itemSets = $item->itemSets(); ?>
		<?php if (count($itemSets) > 0): ?>
		<h3><?php echo $translate('Item sets'); ?></h3>
		<?php foreach ($itemSets as $itemSet): ?>
		<div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
		<?php endforeach; ?>
		<?php endif; ?>
	</div>
</section>

<!-- Thumbnail image -->
<div id="thumbnail">
	<?php if ($itemThumbnail = $this->thumbnail($item, 'large')): ?>
        <?php echo $item->linkRaw($itemThumbnail); ?>
    <?php endif; ?>
</div>

<!-- Show quick links only for items that are part of the item set (Feuilletons) -->
<div id="quick" class="quick">
	<?php $itemSets = $item->itemSets(); ?>
		<?php if (count($itemSets) > 0): ?>
		<ul>
			<li class="link"><a href="#media-embeds">Original Text</a></li>
			<li class="link"><a href="#translation">Translation</a></li>
			<li class="link"><a href="#commentary">Commentary</a></li>
		</ul>
	<?php endif; ?>	
</div>

<section id="metadata" class="metadata">
	<?php echo $item->displayValues(); ?>
</section>

<?php if ($embedMedia && $itemMedia): ?>
  
	<div class="media-embeds" id="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>

<section class="site_pages">
	<?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))): ?>
	<div class="property">
		<h3><?php echo $translate('Site pages'); ?></h3>
		<div class="values">
			<?php foreach ($sitePages as $sitePage): ?>
			<div class="value"><?php echo $sitePage->link($sitePage->title()); ?></div>
			<?php endforeach; ?>
		</div>
	</div>
	<?php endif; ?>
</section>	
<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php echo $media->linkPretty(); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>



<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
