<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$fragment = 'item-linked';
if ('Omeka\Api\Representation\ItemSetRepresentation' === get_class($objectResource)) {
    $fragment = 'item-set-linked';
}
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$pagination->setFragment($fragment);
?>
<div id="linked-resources">
<div class="linked-header">
    <div id="linked-filter">
        <h4><?php echo $translate('Filter by property'); ?></h4>
        <select id="filter-property" name="property" data-url="<?php echo $escape($this->url(null, [], true)); ?>" data-fragment="<?php echo $escape($fragment); ?>">
            <option value=""><?php echo $translate('All'); ?></option>
            <?php foreach ($properties as $prop): ?>
            <option value="<?php echo $escape($prop->id()); ?>"<?php echo $prop->id() == $property ? ' selected="selected"' : ''; ?>><?php echo $escape(sprintf('%s (%s)', $translate($prop->label()), $prop->term())); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php echo ($totalCount > $perPage) ? $pagination : ''; ?>
</div>

<?php foreach ($subjectValues as $term => $values): ?>
<div>
<caption class="linked-resource-property"><?php echo $escape($this->translate($values[0]->property()->label())); ?></caption>

    <?php foreach ($values as $value): ?>
    <?php
    $template = $value->resource()->resourceTemplate();
    $templateProperty = $template ? $template->resourceTemplateProperty($value->property()->id()) : null;
    $altLabel = $templateProperty ? $templateProperty->alternateLabel() : null;
    ?>
    <div class="linked-resource">
        <div><?php echo $value->resource()->linkPretty(); ?>
        <?php if ($altLabel): ?>
        <span class="alternate-label"><?php echo $this->escapeHtml($altLabel); ?></span>
        <?php endif; ?>
       
        <?php if ($value->resource()->resourceClass()): ?>
        <span class="resource-class"><?php echo $this->escapeHtml($translate($value->resource()->resourceClass()->label())); ?></span>
        <?php endif; ?>
        </div>
    </div>
    <?php endforeach; ?>

</div>
<?php endforeach; ?>

<?php echo ($totalCount > $perPage) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>

</div>

<script>
$('#filter-property').on('change', function(e) {
    var thisSelect = $(this);
    var property = thisSelect.find(':selected').val();
    var url = thisSelect.data('url');
    var fragment = thisSelect.data('fragment');
    window.location = url + '?' + $.param({property: property}) + '#' + fragment;
});
</script>
